### ISSUE TITLE
Safe HTML processor gets stuck or runs very slow

### ISSUE THREAD

**Issue by attilahogyai** [kefirfromperm/kefirbb#43]
A safehtml processor instantiated like this:
`TextProcessor safeProcessor = BBProcessorFactory.getInstance().createFromResource("org/kefirsf/bb/safehtml.xml");`
gets stuck or runs very slow during the parsing of a string which contains many <br>s.
Example test case:
`safeProcessor.process("<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>");`
The issue exists in version 1.0 and 1.2 as well.

**Comment by kefirfromperm** [comment]
Thank you for your issue.

To resolve this bug you can use [the latest safe HTML configuration](https://github.com/kefirfromperm/kefirbb/blob/master/src/org/kefirsf/bb/safehtml.xml). Just rename it to kefirbb.xml and put in classpath.

I recommend to use your own configuration based on standard one.

**Comment by attilahogyai** [comment]
Thank you for quick fix and advise!

**Comment by kefirfromperm** [comment]
Resolved in version 1.3
